---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/nicolaboscolo/Documents/concurrentAndRealtime/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _producer, symObjAddr: 0x0, symBinAddr: 0x100003A38, symSize: 0x120 }
  - { offsetInCU: 0x3F, offset: 0x3F, size: 0x8, addend: 0x0, symName: _mutex, symObjAddr: 0x410, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0xAC, offset: 0xAC, size: 0x8, addend: 0x0, symName: _cond, symObjAddr: 0x450, symBinAddr: 0x100008040, symSize: 0x0 }
  - { offsetInCU: 0x104, offset: 0x104, size: 0x8, addend: 0x0, symName: _queueSize, symObjAddr: 0x18D4, symBinAddr: 0x100008078, symSize: 0x0 }
  - { offsetInCU: 0x120, offset: 0x120, size: 0x8, addend: 0x0, symName: _productionRate, symObjAddr: 0x480, symBinAddr: 0x100008070, symSize: 0x0 }
  - { offsetInCU: 0x135, offset: 0x135, size: 0x8, addend: 0x0, symName: _messageQueue, symBinAddr: 0x100008088, symSize: 0x0 }
  - { offsetInCU: 0x156, offset: 0x156, size: 0x8, addend: 0x0, symName: _fptr, symBinAddr: 0x100008080, symSize: 0x0 }
  - { offsetInCU: 0x354, offset: 0x354, size: 0x8, addend: 0x0, symName: _producer, symObjAddr: 0x0, symBinAddr: 0x100003A38, symSize: 0x120 }
  - { offsetInCU: 0x38A, offset: 0x38A, size: 0x8, addend: 0x0, symName: _consumer, symObjAddr: 0x120, symBinAddr: 0x100003B58, symSize: 0xA4 }
  - { offsetInCU: 0x3B2, offset: 0x3B2, size: 0x8, addend: 0x0, symName: _lengthChecker, symObjAddr: 0x1C4, symBinAddr: 0x100003BFC, symSize: 0x178 }
  - { offsetInCU: 0x3DA, offset: 0x3DA, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x33C, symBinAddr: 0x100003D74, symSize: 0xD4 }
...
